Vagrant.configure(2) do |config|
  config.vm.box = "centos-6.5x64"
  config.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box"
  config.vm.hostname = "web-ap"

  # network configuration
  config.vm.network "public_network", ip: "172.19.1.2"
  config.vm.network "private_network", ip: "10.255.1.2"
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.provider "virtualbox" do |vm|
    vm.memory = 6144
  end

end

# Provision Common Configurations
load "../Vagrantfile.common" if File.exist?("../Vagrantfile.common")

# Provision Configuration for AP Server
Vagrant.configure(2) do |config|
  config.vm.provision :shell, :path => "./bootstrap.sh"
end
